# Generated by Django 4.1.dev20211203115706 on 2021-12-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('taille', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('semis', models.CharField(max_length=100)),
                ('recolte', models.CharField(max_length=100)),
                ('besoin_eau', models.IntegerField()),
                ('besoin_temperature', models.IntegerField()),
            ],
        ),
    ]
