# Generated by Django 4.1.dev20211203115706 on 2021-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_parcelle_semence_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
