# Generated by Django 4.1.dev20211203115706 on 2021-12-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_annee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee',
            name='parcelles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alpha.parcelle'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='semence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alpha.semence'),
        ),
    ]
