# Generated by Django 4.1.dev20211203115706 on 2021-12-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_alter_annee_parcelles_alter_parcelle_semence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annee',
            name='parcelles',
        ),
        migrations.AddField(
            model_name='annee',
            name='parcelles',
            field=models.ManyToManyField(to='alpha.Parcelle'),
        ),
    ]
