# Generated by Django 4.1.dev20211203115706 on 2021-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0005_remove_annee_parcelles_annee_parcelles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annee',
            name='parcelles',
        ),
        migrations.AddField(
            model_name='parcelle',
            name='annees',
            field=models.ManyToManyField(to='alpha.Annee'),
        ),
    ]
