# Generated by Django 4.1.dev20211203115706 on 2021-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0006_remove_annee_parcelles_parcelle_annees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='annees',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='semence',
        ),
        migrations.AddField(
            model_name='parcelle',
            name='annee_semence',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
